### ISSUE TITLE
The sign out button on mobile doesn't redirect to the home / login page

### ISSUE THREAD

**Issue by ridvanmaulana** [Tanvir-Alam625/Threads#12]
The sign out button on mobile doesn't redirect to the home / login page... I tried changing it with <UserButton.... then it works. and how to create a thread with the community? I've tried switching to the profile community, but it still fails to post. Is there any setting that I missed?

**Comment by Tanvir-Alam625** [comment]
I've encountered an issue where the sign-out button isn't working correctly on mobile. I fixed it by replacing the button with <UserButton... Any insights or solutions for mobile-specific sign-out button issues? Thanks!
